# 6.1 Data Cleaning, Consistency Checks & Descriptive Analysis

In [1]:
# Import libraries
import pandas as pd
import numpy as np
import os

## 1) Import and Explore Dataset

In [2]:
# Import data set
path = r'/Users/minglunchen/Desktop/A6_Project_Yiru'

In [3]:
df_heart = pd.read_csv(os.path.join(path, '02 Data', 'Original Data', 'heart_2022_no_nans.csv'), index_col = False)

In [4]:
# Get the overview of the heart disease data set by looking at first 5 rows
df_heart.head()

,State,Sex,GeneralHealth,PhysicalHealthDays,MentalHealthDays,LastCheckupTime,PhysicalActivities,SleepHours,RemovedTeeth,HadHeartAttack,...,HeightInMeters,WeightInKilograms,BMI,AlcoholDrinkers,HIVTesting,FluVaxLast12,PneumoVaxEver,TetanusLast10Tdap,HighRiskLastYear,CovidPos
0,Alabama,Female,Very good,4.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.60,71.67,27.99,No,No,Yes,Yes,"Yes, received Tdap",No,No
1,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,Yes,6.0,None of them,No,...,1.78,95.25,30.13,No,No,Yes,Yes,"Yes, received tetanus shot but not sure what type",No,No
2,Alabama,Male,Very good,0.0,0.0,Within past year (anytime less than 12 months ...,No,8.0,"6 or more, but not all",No,...,1.85,108.86,31.66,Yes,No,No,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
3,Alabama,Female,Fair,5.0,0.0,Within past year (anytime less than 12 months ...,Yes,9.0,None of them,No,...,1.70,90.72,31.32,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,Yes
4,Alabama,Female,Good,3.0,15.0,Within past year (anytime less than 12 months ...,Yes,5.0,1 to 5,No,...,1.55,79.38,33.07,No,No,Yes,Yes,"No, did not receive any tetanus shot in the pa...",No,No

In [5]:
# Check the shape (column & rows) of the data set
df_heart.shape

(246022, 40)

In [6]:
# Get the basic statistics for quantitative variables
df_heart.describe()

,PhysicalHealthDays,MentalHealthDays,SleepHours,HeightInMeters,WeightInKilograms,BMI
count,246022.000000,246022.000000,246022.000000,246022.000000,246022.000000,246022.000000
mean,4.119026,4.167140,7.021331,1.705150,83.615179,28.668136
std,8.405844,8.102687,1.440681,0.106654,21.323156,6.513973
min,0.000000,0.000000,1.000000,0.910000,28.120000,12.020000
25%,0.000000,0.000000,6.000000,1.630000,68.040000,24.270000
50%,0.000000,0.000000,7.000000,1.700000,81.650000,27.460000
75%,3.000000,4.000000,8.000000,1.780000,95.250000,31.890000
max,30.000000,30.000000,24.000000,2.410000,292.570000,97.650000

In [7]:
# Check the counts and data type of variables
df_heart.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 246022 entries, 0 to 246021
Data columns (total 40 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   State                      246022 non-null  object
 1   Sex                        246022 non-null  object
 2   GeneralHealth              246022 non-null  object
 3   PhysicalHealthDays         246022 non-null  float64
 4   MentalHealthDays           246022 non-null  float64
 5   LastCheckupTime            246022 non-null  object
 6   PhysicalActivities         246022 non-null  object
 7   SleepHours                 246022 non-null  float64
 8   RemovedTeeth               246022 non-null  object
 9   HadHeartAttack             246022 non-null  object
 10  HadAngina                  246022 non-null  object
 11  HadStroke                  246022 non-null  object
 12  HadAsthma                  246022 non-null  object
 13  HadSkinCancer              246022 non-null  object
 14  HadCOPD                    246022 non-null  object
 15  HadDepressiveDisorder      246022 non-null  object
 16  HadKidneyDisease           246022 non-null  object
 17  HadArthritis               246022 non-null  object
 18  HadDiabetes                246022 non-null  object
 19  DeafOrHardOfHearing        246022 non-null  object
 20  BlindOrVisionDifficulty    246022 non-null  object
 21  DifficultyConcentrating    246022 non-null  object
 22  DifficultyWalking          246022 non-null  object
 23  DifficultyDressingBathing  246022 non-null  object
 24  DifficultyErrands          246022 non-null  object
 25  SmokerStatus               246022 non-null  object
 26  ECigaretteUsage            246022 non-null  object
 27  ChestScan                  246022 non-null  object
 28  RaceEthnicityCategory      246022 non-null  object
 29  AgeCategory                246022 non-null  object
 30  HeightInMeters             246022 non-null  float64
 31  WeightInKilograms          246022 non-null  float64
 32  BMI                        246022 non-null  float64
 33  AlcoholDrinkers            246022 non-null  object
 34  HIVTesting                 246022 non-null  object
 35  FluVaxLast12               246022 non-null  object
 36  PneumoVaxEver              246022 non-null  object
 37  TetanusLast10Tdap          246022 non-null  object
 38  HighRiskLastYear           246022 non-null  object
 39  CovidPos                   246022 non-null  object
dtypes: float64(6), object(34)
memory usage: 75.1+ MB

## 2) Data Quality and Consistency Checks

In [8]:
# Check for mixed type
for col in df_heart.columns.tolist():
    weird = (df_heart[[col]].map(type) != df_heart[[col]].iloc[0].apply(type)).any(axis = 1)
    if len (df_heart[weird]) > 0:
        print(col)

*No mixed type was observed.*

In [9]:
# Find missing values
df_heart.isnull().sum()

State                        0
Sex                          0
GeneralHealth                0
PhysicalHealthDays           0
MentalHealthDays             0
LastCheckupTime              0
PhysicalActivities           0
SleepHours                   0
RemovedTeeth                 0
HadHeartAttack               0
HadAngina                    0
HadStroke                    0
HadAsthma                    0
HadSkinCancer                0
HadCOPD                      0
HadDepressiveDisorder        0
HadKidneyDisease             0
HadArthritis                 0
HadDiabetes                  0
DeafOrHardOfHearing          0
BlindOrVisionDifficulty      0
DifficultyConcentrating      0
DifficultyWalking            0
DifficultyDressingBathing    0
DifficultyErrands            0
SmokerStatus                 0
ECigaretteUsage              0
ChestScan                    0
RaceEthnicityCategory        0
AgeCategory                  0
HeightInMeters               0
WeightInKilograms            0
BMI                          0
AlcoholDrinkers              0
HIVTesting                   0
FluVaxLast12                 0
PneumoVaxEver                0
TetanusLast10Tdap            0
HighRiskLastYear             0
CovidPos                     0
dtype: int64

*No missing value were found.*

In [10]:
# Find duplicates
df_heart.duplicated()

0         False
1         False
2         False
3         False
4         False
          ...
246017    False
246018    False
246019    False
246020    False
246021    False
Length: 246022, dtype: bool

*No duplicates were found.*

**Conclusion**: The data set is clean, well-structured without missing values and duplicates. 
It is ready for the further analysis.